# Generated by Django 4.2 on 2023-04-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nomi')),
                ('summa', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'iPhone',
                'verbose_name_plural': 'iPhonelar',
            },
        ),
        migrations.CreateModel(
            name='Metto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('model', models.CharField(max_length=255, verbose_name='madel')),
            ],
            options={
                'verbose_name': 'Telefon',
                'verbose_name_plural': 'Telefonlar',
            },
        ),
    ]
